# Generated by Django 5.2 on 2025-05-30 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_alter_history_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
