# Generated by Django 5.2 on 2025-06-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_delete_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='program',
            field=models.CharField(default='Ninguno', max_length=40),
        ),
        migrations.AddField(
            model_name='profile',
            name='telephone_number',
            field=models.CharField(default='+57 3001234567', max_length=20),
        ),
    ]
