# Generated by Django 5.2 on 2025-06-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_profile_level_profile_program_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telephone_number',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
