# Generated by Django 5.2 on 2025-05-12 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_availablequiz_options_alter_quiz_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='id_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='quiz.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='id_quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='quiz.quiz'),
        ),
    ]
