# Generated by Django 5.2 on 2025-05-12 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_answer_id_question_alter_question_id_quiz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='id_quiz',
            new_name='quiz',
        ),
    ]
