# Generated by Django 5.2 on 2025-05-12 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_rename_id_quiz_question_quiz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='id_question',
            new_name='question',
        ),
    ]
