# Generated by Django 5.2 on 2025-05-12 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_rename_id_question_answer_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availablequiz',
            old_name='id_quiz',
            new_name='quiz',
        ),
        migrations.RenameField(
            model_name='availablequiz',
            old_name='id_usuario',
            new_name='user',
        ),
    ]
