# Generated by Django 5.2 on 2025-05-30 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_rename_id_quiz_quizcompletion_quiz_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='id_lecture',
            new_name='lecture',
        ),
    ]
