# Generated by Django 5.2 on 2025-05-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_lecture_lecture_in_section_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_in_section_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lecturecontent',
            name='content_in_lecture_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_number',
            field=models.IntegerField(default=0),
        ),
    ]
