# Generated by Django 5.2 on 2025-05-29 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_alter_lecture_lecture_in_section_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturecontent',
            old_name='content_path',
            new_name='content',
        ),
    ]
