# Generated by Django 5.2 on 2025-05-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_rename_content_path_lecturecontent_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturecontent',
            name='content',
            field=models.CharField(max_length=1000),
        ),
    ]
