# Generated by Django 5.2 on 2025-05-29 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_alter_lecturecontent_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lectureavailabilityandcompletion',
            old_name='id_lecture',
            new_name='lecture_id',
        ),
        migrations.RenameField(
            model_name='lectureavailabilityandcompletion',
            old_name='id_user',
            new_name='user_id',
        ),
    ]
