# Generated by Django 5.2 on 2025-05-30 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_rename_id_lecture_lectureavailabilityandcompletion_lecture_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='section_id',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='lectureavailabilityandcompletion',
            old_name='lecture_id',
            new_name='lecture',
        ),
        migrations.RenameField(
            model_name='lectureavailabilityandcompletion',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='lecturecontent',
            old_name='lecture_id',
            new_name='lecture',
        ),
    ]
