# Generated by Django 5.2 on 2025-06-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_rename_section_id_lecture_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='description',
            field=models.CharField(default='Description', max_length=500, null=True),
        ),
    ]
